### ISSUE TITLE
QGIS "No symbols" renderer

### ISSUE THREAD

**Issue by tomchadwin** [GeoCat/bridge-style#22]
I think the QGIS "No symbols" renderer might not be supported, leading to an error. Does anyone else confirm?

**Comment by pvgenuchten** [comment]
true, no-symbol gives this error

```
KeyError: 'rules' 
Traceback (most recent call last):
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 46, in updateLayer
    self.updateForCurrentLayer()
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 56, in updateForCurrentLayer
    sld, _, sldWarnings = layerStyleAsSld(layer)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/__init__.py", line 15, in layerStyleAsSld
    sldString, sldWarnings = sld.fromgeostyler.convert(geostyler)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/sld/fromgeostyler.py", line 33, in convert
    for rule in geostyler["rules"]:
KeyError: 'rules'
```
