### ISSUE TITLE
MapboxGL: offset error

### ISSUE THREAD

**Issue by tomchadwin** [GeoCat/bridge-style#32]
I think this is caused by QGIS labels on line geometries:

```
TypeError: 'float' object is not subscriptable 
Traceback (most recent call last):
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 190, in changeFormat
    self.autoUpdatePreview()
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in autoUpdatePreview
    self.previewMap()
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 337, in previewMap
    preview_file = self.createPreview()
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 300, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxWriter.py", line 103, in write
    folder=dest_folder)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxWriter.py", line 279, in writeMapbox
    vLayers)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxLayerScripts.py", line 145, in writeVectorLayer
    mblayers = getLayerStyle(layer)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxStyleScripts.py", line 43, in getLayerStyle
    mapboxStyle = bridgestyle.qgis.layerStyleAsMapbox(layer)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\bridgestyle\qgis\__init__.py", line 36, in layerStyleAsMapbox
    mbox, mbWarnings = mapboxgl.fromgeostyler.convert(geostyler)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\bridgestyle\mapboxgl\fromgeostyler.py", line 10, in convert
    layers = processLayer(geostyler)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\bridgestyle\mapboxgl\fromgeostyler.py", line 30, in processLayer
    layers = processRule(rule, layer["name"])
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\bridgestyle\mapboxgl\fromgeostyler.py", line 46, in processRule
    layers = [processSymbolizer(s) for s in rule["symbolizers"]]
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\bridgestyle\mapboxgl\fromgeostyler.py", line 46, in 
    layers = [processSymbolizer(s) for s in rule["symbolizers"]]
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\bridgestyle\mapboxgl\fromgeostyler.py", line 125, in processSymbolizer
    symbolizer = _textSymbolizer(sl)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\bridgestyle\mapboxgl\fromgeostyler.py", line 150, in _textSymbolizer
    offsetx = convertExpression(offset[0])
TypeError: 'float' object is not subscriptable
```

**Comment by tomchadwin** [comment]
Apologies: duplicate of #7, I think.

**Comment by tomchadwin** [comment]
Not a duplicate: different issue, occurs in master. A `try:` "fixes" it by changing:

```python
offsetx = convertExpression(offset[0])
offsety = convertExpression(offset[1])
```

to:

```python
try:
    offsetx = convertExpression(offset[0])
    offsety = convertExpression(offset[1])
except TypeError:
    offsetx = convertExpression(offset)
    offsety = convertExpression(offset)
```
